### ISSUE TITLE
Cannot read property 'exports' of undefined

### ISSUE THREAD

**Issue by DeFuex** [conorhastings/react-syntax-highlighter#10] opened 2016-05-18 11:22 UTC
Hi,

first of all, thanks for this awesome project.

A few days ago everything worked fine for me. Now if i npm start my project, the console tells me that some method of highlight.js -> 

`.... module.exports = function(hljs) {
	  var CPP = hljs.getLanguage('cpp').exports; .....`

seems to have following problem "Cannot read property 'exports' of undefined". Could it be that it has to do with Babel 6 features for export -> https://github.com/webpack/webpack/issues/706? I tried to fix this myself, but failed until now. Maybe you can tell me whats this about? Would be awesome. Thanks!

**EDIT:**
Possible solution 
http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
https://www.npmjs.com/package/babel-plugin-add-module-exports

kind regards,
defuex

**Comment by conorhastings** [comment] 2016-05-18 14:12
hey thanks for the issue, I'll try to look into this, this evening.

**Comment by conorhastings** [comment] 2016-05-18 17:48
@DeFuex by the way if you have any sample code reproducing the issue, that would be great!

**Comment by DeFuex** [comment] 2016-05-18 18:03
sure thing, go to my develop branch https://github.com/DeFuex/Blogolio/tree/develop and pull my portfolio webpage, make an npm install and npm start. if i take out the component were syntax highlighting is used everything works fine.

**Comment by conorhastings** [comment] 2016-05-19 01:03
@DeFuex It seems to be an issue with `highlight.js@9.4.0` , I haven't pinpointed the exact cause yet but moving to a hard dep on `9.3.0` fixed the issue. I published `2.0.4` as a stopgap while I investigate further. Thanks again for bringing this to my attention!

**Comment by conorhastings** [comment] 2016-05-19 01:10
here is the offending line of code, https://github.com/isagalaev/highlight.js/compare/9.3.0...9.4.0#diff-b4721ca0cfdcb6627474ae5357615f51R9 , still not sure why it causes this issue.

**Comment by DeFuex** [comment] 2016-05-19 07:50
@conorhastings np, thx for the quick fix :)

**Comment by wooorm** [comment] 2016-05-19 15:40
@conorhastings I believe this is a problem with highlight.js not honouring semver, right? Does that mean lowlight itself should use `~` instead of `^` in its dependency?

**Comment by conorhastings** [comment] 2016-05-19 17:07
@wooorm I think in light of this, that sounds like the right move!

**Comment by wooorm** [comment] 2016-05-19 17:16
OK, I did, and released lowlight@1.2.0 with fixes, and a locked highlight.js@9.4.0

**Comment by wooorm** [comment] 2016-05-21 09:00
@conorhastings This can be closed, right?

**Comment by conorhastings** [comment] 2016-05-21 12:37
@wooorm yup!

**Closed by conorhastings** 2016-05-21 12:37 UTC
