### ISSUE TITLE
registerLanguage not exported 

### ISSUE THREAD

**Issue by shanedaugherty** [conorhastings/react-syntax-highlighter#106] opened 2018-02-28 14:45 UTC
Getting this error when using the example code from the docs: 

```
import SyntaxHighlighter, { registerLanguage } from "react-syntax-highlighter/prism-light";
import jsx from 'react-syntax-highlighter/languages/prism/jsx';
import prism from 'react-syntax-highlighter/styles/prism/prism'; 

registerLanguage('jsx', jsx);
```

```
(0 , _prism.registerLanguage) is not a function
```

**Comment by conorhastings** [comment] 2018-03-03 11:34
I'm unable to reproduce -- https://codesandbox.io/s/6ro18o3r3. -- perhaps a problem with your build setup?

**Comment by conorhastings** [comment] 2018-03-21 01:07
closing, feel free to reopen with reproducable case

**Closed by conorhastings** 2018-03-21 01:07 UTC
